is_ub_added: True
# 'exact' will call the exact method,
# 'greedy' wil call the greedy method, otherwise no lb info is returned.
is_lb_added: 'exact'

model_name: 'coloring'
mip_gap: 0
time_limit: 7200

#input_files: [ 'myciel6.col', 'myciel7.col', 'le450_15b.col', 'le450_15c.col', 'le450_15d.col']
input_files: [ 'le450_15b.col' ]

parse_iter: True